sequenceDiagram
    actor KM as КМ
    actor S as Поставщик
    participant TB as Telegram-бот
    participant API as API-сервис
    participant PO as ПП-Odoo
    participant O as Система Odoo

    KM ->>+ TB: Ввод телефона КМ
    Note over TB: Проверка телефона КМ в базе
    alt Телефон КМ не найден
        TB -->> KM: Сообщение "КМ не найден"
    else Телефон КМ найден
        TB -->> KM: Запрос телефона поставщика
        KM ->>+ TB: Ввод телефона поставщика
        TB ->>+ API: Запрос создания поставщика
        API ->>+ O: Создание поставщика
        alt Поставщик существует
            O -->> API: Ошибка "Поставщик существует"
            API -->> TB: Ошибка
            TB -->> KM: Сообщение об ошибке
        else Успешно
            O -->> API: Данные доступа
            API -->> TB: Данные доступа
            TB -->> KM: Данные для поставщика
            KM -->> S: Передача данных доступа
            S ->>+ PO: Вход по ссылке
            PO -->> S: Запрос смены пароля
            S ->> PO: Новый пароль
            S ->> PO: Заполнение обязательных данных
            PO ->> O: Сохранение данных
        end
    end